### ISSUE TITLE
稀疏训练加载模型时遇到的问题

### ISSUE THREAD

**Issue by 15050188022** [jiachengjiacheng/Pruned-YOLO#5]
![image](https://user-images.githubusercontent.com/30464411/120580255-6fb2f800-c45b-11eb-88b7-cfa3c723e4c0.png)
我在稀疏训练时使用YOLOv54.0版本，请问在加载模型时为什么会遇到这个问题呢

**Comment by jiachengjiacheng** [comment]
> ![image](https://user-images.githubusercontent.com/30464411/120580255-6fb2f800-c45b-11eb-88b7-cfa3c723e4c0.png)
> 我在稀疏训练时使用YOLOv54.0版本，请问在加载模型时为什么会遇到这个问题呢

将 state_dict = ckpt['model']注释，反注释state_dict = ckpt['model'].float().state_dict() 试试

**Comment by 15050188022** [comment]
> > ![image](https://user-images.githubusercontent.com/30464411/120580255-6fb2f800-c45b-11eb-88b7-cfa3c723e4c0.png)
> > 我在稀疏训练时使用YOLOv54.0版本，请问在加载模型时为什么会遇到这个问题呢
> 
> 将 state_dict = ckpt['model']注释，反注释state_dict = ckpt['model'].float().state_dict() 试试

还是不行诶，依旧是模型加载的问题。
![image](https://user-images.githubusercontent.com/30464411/122177749-7d836700-ceb8-11eb-8106-ed5e6e48b13b.png)

**Comment by jiachengjiacheng** [comment]
> > > ![image](https://user-images.githubusercontent.com/30464411/120580255-6fb2f800-c45b-11eb-88b7-cfa3c723e4c0.png)
> > > 我在稀疏训练时使用YOLOv54.0版本，请问在加载模型时为什么会遇到这个问题呢
> > 
> > 
> > 将 state_dict = ckpt['model']注释，反注释state_dict = ckpt['model'].float().state_dict() 试试
> 
> 还是不行诶，依旧是模型加载的问题。
> ![image](https://user-images.githubusercontent.com/30464411/122177749-7d836700-ceb8-11eb-8106-ed5e6e48b13b.png)

这已经不是原来的问题了，这个bug很可能是某一层的参数名字对不齐，你可以看一下模型的参数名和load进来的参数字典中存的参数名是否有差异。另一种粗暴的解决方法是设置strict=False，这样设置的话不对齐的参数就不会load了。

**Comment by Huangjiajing96** [comment]
我在训练时也遇到了同样的问题，请问您有找到解决办法吗 @15050188022

**Comment by DFXX34** [comment]
我在进行prune_layer时出现了下面的报错，我需要怎么解决

Traceback (most recent call last):
  File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 240, in <module>
    prune(opt, device)
  File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 217, in prune
    destination_cfg = write_config_py(opt.cfg, save, grab_ifo_layer_idx, grab_ifo_layer_num)
  File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 113, in write_config_py
    model_dict['backbone'][i][-1][-1] = model_dict['backbone'][i][-1][-1][:grab_ifo_layer_num[j]]
TypeError: 'int' object is not subscriptable

**Comment by DFXX34** [comment]
#使用prune_layer出现问题
我在进行prune_layer时出现了下面的报错，我需要怎么解决

Traceback (most recent call last):
File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 240, in
prune(opt, device)
File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 217, in prune
destination_cfg = write_config_py(opt.cfg, save, grab_ifo_layer_idx, grab_ifo_layer_num)
File "D:\yolov5\yolov5-master\prune_layer_v5_weightingByKernel.py", line 113, in write_config_py
model_dict['backbone'][i][-1][-1] = model_dict['backbone'][i][-1][-1][:grab_ifo_layer_num[j]]
TypeError: 'int' object is not subscriptable
