### ISSUE TITLE
使用prune-channel剪枝出现的问题

### ISSUE THREAD

**Issue by leng17** [jiachengjiacheng/Pruned-YOLO#9]
使用prune_channel_v5_weightingByKernel剪枝后的网络，在进行test.py和train.py都出现了问题。
Traceback (most recent call last):
  File "D:/baiduwangpan/yolov5/yolov55/test.py", line 323, in <module>
    save_conf=opt.save_conf,
  File "D:/baiduwangpan/yolov5/yolov55/test.py", line 56, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "D:\baiduwangpan\yolov5\yolov55\models\experimental.py", line 119, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
AttributeError: 'dict' object has no attribute 'float'
但是使用prune_layer_v5_weightingByKernel层剪枝后的网络是没有问题的。我查看了剪枝后的网络保存的形式。层剪枝和原始网络是一样的，通道剪枝不一样。请问这怎么解决呢？

**Comment by Jack-liu1998** [comment]
train中state_dict = ckpt['model'].float().state_dict()需要改为state_dict = ckpt['model']
